#!/bin/sh

cat /dev/null > log
for size in 10
do
	for order in random #sorted reverse
	do
		echo === Testing for $order input, size $size === >> log
		for i in 1 2 3 4 5 6 7
		do
			case $order in
			random) flag="R" ;;
			sorted) flag="A" ;;
			reverse) flag="D" ;;
			esac
			{ ./gen $size $flag | time ./sortB > /dev/null ; } 2>> log
		done
		echo "XJ" >> log
	done
done
